void init(void);
void wait(unsigned);
void toggleA0(void);
void setLEDs(char);
void pwmServo(unsigned);
char getPath(void);
unsigned getVoltage(void);
unsigned getCount(void);
unsigned wait_count(unsigned start, unsigned);
unsigned wait_count(unsigned);
void poll(unsigned);
bool uart3_print(const char* p);
bool uart3_read(char &c);
bool uart2_print(const char* p);
void loop_remote(void);
void dirLeft(bool b);
void dirRight(bool b);
void pwmLeft(unsigned i);
void pwmRight(unsigned i);
void left_wheel_forward(void);
void Right_wheel_forward(void);
void left_wheel_backward(void);
void Right_wheel_backward(void);
void wheel_forward(void);
void wheel_backward(void);
void wheel_left (void);
void wheel_right (void);
void wheel_forward_fast(void);
void wheel_backward_fast(void);
